
import java.sql.*;
import Project.ConnectionProvider;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author matdef
 */
public class DeleteQuestion extends javax.swing.JFrame {

    /**
     * Creates new form DeleteQuestion
     */
    public DeleteQuestion() {
        initComponents();
        this.setSelectedId(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        QuestionIdLabel = new javax.swing.JLabel();
        Option1Label = new javax.swing.JLabel();
        Option2Label = new javax.swing.JLabel();
        Option3Label = new javax.swing.JLabel();
        Option4Label = new javax.swing.JLabel();
        AnswerLabel = new javax.swing.JLabel();
        QuestionIdField = new javax.swing.JTextField();
        QuestionField = new javax.swing.JTextField();
        Option2Field = new javax.swing.JTextField();
        Option1Field = new javax.swing.JTextField();
        AnswerField = new javax.swing.JTextField();
        Option4Field = new javax.swing.JTextField();
        Option3Field = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Bevan", 0, 40)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete Question.png"))); // NOI18N
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setText("DELETE QUESTION");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Question:");

        QuestionIdLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        QuestionIdLabel.setText("Question ID:");

        Option1Label.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Option1Label.setText("Option 1:");

        Option2Label.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Option2Label.setText("Option 2:");

        Option3Label.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Option3Label.setText("Option 3:");

        Option4Label.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Option4Label.setText("Option 4:");

        AnswerLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        AnswerLabel.setText("Answer:");

        QuestionIdField.setText("Question ID to search");
        QuestionIdField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestionIdFieldMouseClicked(evt);
            }
        });
        QuestionIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionIdFieldActionPerformed(evt);
            }
        });

        QuestionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionFieldActionPerformed(evt);
            }
        });

        Option2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option2FieldActionPerformed(evt);
            }
        });

        Option1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option1FieldActionPerformed(evt);
            }
        });

        AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerFieldActionPerformed(evt);
            }
        });

        Option4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option4FieldActionPerformed(evt);
            }
        });

        Option3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option3FieldActionPerformed(evt);
            }
        });

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 940, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QuestionIdLabel)
                    .addComponent(jLabel2)
                    .addComponent(Option1Label)
                    .addComponent(Option2Label)
                    .addComponent(Option3Label)
                    .addComponent(Option4Label)
                    .addComponent(AnswerLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(ClearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuestionIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton))
                    .addComponent(Option1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Option2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Option3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Option4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AnswerLabel, Option1Label, Option2Label, Option3Label, Option4Label, QuestionIdLabel, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AnswerField, Option1Field, Option2Field, Option3Field, Option4Field, QuestionField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ClearButton, DeleteButton, SearchButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuestionIdLabel)
                    .addComponent(QuestionIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(QuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Option1Label)
                    .addComponent(Option1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Option2Label)
                    .addComponent(Option2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Option3Label)
                    .addComponent(Option3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Option4Label)
                    .addComponent(Option4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnswerLabel)
                    .addComponent(AnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton)
                    .addComponent(ClearButton))
                .addContainerGap(411, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AnswerLabel, Option1Label, Option2Label, Option3Label, Option4Label, QuestionIdField, QuestionIdLabel, jLabel2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuestionIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionIdFieldActionPerformed

    private void QuestionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionFieldActionPerformed

    private void Option2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option2FieldActionPerformed

    private void Option1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option1FieldActionPerformed

    private void AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerFieldActionPerformed

    private void Option4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option4FieldActionPerformed

    private void Option3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option3FieldActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        AdminHome.open = 0;
        setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void QuestionIdFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestionIdFieldMouseClicked
        QuestionIdField.setText("");
    }//GEN-LAST:event_QuestionIdFieldMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        String questionId = QuestionIdField.getText();
        if (questionId.isEmpty()) {
            return;
        }
        try {
            Integer.valueOf(questionId);
            if (Integer.parseInt(questionId) < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid ID: ID must be an integer greater than 0", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            PreparedStatement ps = ConnectionProvider.getConn().prepareStatement("SELECT * FROM question WHERE id = ?");
            ps.setInt(1, Integer.parseInt(questionId));
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.setSelectedId(rs.getInt(1));
                this.QuestionField.setText(rs.getString(2));
                this.Option1Field.setText(rs.getString(3));
                this.Option2Field.setText(rs.getString(4));
                this.Option3Field.setText(rs.getString(5));
                this.Option4Field.setText(rs.getString(6));
                this.AnswerField.setText(rs.getString(7));
            }
        } catch (NumberFormatException e) {
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Something went wrong!\n" + e, "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (this.getSelectedId() == -1) {
            JOptionPane.showMessageDialog(null, String.format("Question with ID: %d was not found!", Integer.parseInt(questionId)), "Not found!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_SearchButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        Integer id = this.getSelectedId();

        if (id == -1) {
            JOptionPane.showMessageDialog(null, "Please search for and select a question ID first.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Integer choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the question with the ID: " + id, "Confirmation", JOptionPane.OK_CANCEL_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            try {
                ConnectionProvider.getConn().createStatement().execute("DELETE FROM question WHERE id = " + id);
            } catch (SQLException ex) {
                Logger.getLogger(DeleteQuestion.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Something went wrong!\n" + ex, "Error!", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, String.format("Question with ID: %d has been deleted", id), "Success!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
        QuestionIdField.setText("");
        QuestionField.setText("");
        AnswerField.setText("");
        Option1Field.setText("");
        Option2Field.setText("");
        Option3Field.setText("");
        Option4Field.setText("");
        this.setSelectedId(-1);
    }//GEN-LAST:event_ClearButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteQuestion().setVisible(true);
            }
        });
    }

    private Integer selectedId;

    private Integer getSelectedId() {
        return selectedId;
    }

    private void setSelectedId(Integer id) {
        this.selectedId = id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerField;
    private javax.swing.JLabel AnswerLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField Option1Field;
    private javax.swing.JLabel Option1Label;
    private javax.swing.JTextField Option2Field;
    private javax.swing.JLabel Option2Label;
    private javax.swing.JTextField Option3Field;
    private javax.swing.JLabel Option3Label;
    private javax.swing.JTextField Option4Field;
    private javax.swing.JLabel Option4Label;
    private javax.swing.JTextField QuestionField;
    private javax.swing.JTextField QuestionIdField;
    private javax.swing.JLabel QuestionIdLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
